### PR TITLE
Unipool rewards

### PR DESCRIPTION
**Pull request by fabriziovigevani**
UI for displaying connected account´s accrued rewards and button to claim the
Screen Shot 2021-09-19 at 17 06 52
m.

### CODE REVIEW

**Review by 0xGabi — APPROVED** [review]
Well done! Looking great 🙌

**Comment by rperez89** [comment]
@fabriziovigevani just one cosmetic comment, what do you think if we center the earn rewards section and remove the vertical line from it so the rewards takes the whole down section of the component instead of being on the right and leaving big blank space on the left?

**Comment by 0xmiel** [comment]
not sure. I think it's nice this way because it makes it clear that the earned rewards are directly related to the gBright - i'm also not convinced it would look good centered.

**Comment by 0xmiel** [comment]
i don't find it awkward tbh

**Pull request merged**
