### PR TITLE
add forum to header

### PR DESCRIPTION
**Pull request by 0xmiel**
Bright [feature request](https://discord.com/channels/698287700834517064/754870015357878304/889762548285583430)

### CODE REVIEW

**Review by Harthor — COMMENTED** [review]
Ran it locally, only issue is that every time I click forum it leads to 1hive's forum, on any dao, I'm not sure why that is.
Could be that it is the default and people haven't put another forum when creating the daos.

**Comment by 0xmiel** [comment]
The forum link for the most recent Bright test DAO correctly links to their forum

https://honey-pot-git-forum-header-1hive.vercel.app/#/garden/0xbb7cc1fd15ee7071f93658d5c46fee41433a5a0b

**Comment by Harthor** [comment]
> The forum link for the most recent Bright test DAO correctly links to their forum
> 
> https://honey-pot-git-forum-header-1hive.vercel.app/#/garden/0xbb7cc1fd15ee7071f93658d5c46fee41433a5a0b

yep, that one works (can see the vercel deployment), not sure how to test it locally though, when running yarn start:xdai , getting errors

**Review by 0xGabi — APPROVED** [review]
Looking good!

**Comment by Harthor** [comment]
> REACT_APP_ETH_NODE=https://rpc.xdaichain.com/ yarn start:xdai

Awesome!! it worked, but the link even on brightid dao on xdai still taking me to 1hive's forum @0xmiel

**Comment by Harthor** [comment]
well it's merged already

**Pull request merged**
